# EchoChain - Data Understanding

## Objective

This notebook explores and understands the datasets used in the EchoChain project.

Datasets:
- Laptop Dataset
- Warranty Dataset
- eBay Dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
laptop = pd.read_csv("../data/raw/laptop_dataset.csv")
warranty = pd.read_csv("../data/raw/warranty_dataset.csv")
ebay = pd.read_csv("../data/raw/Ebay_dataset.csv")

In [3]:
print("Laptop Dataset Shape:", laptop.shape)
print("Warranty Dataset Shape:", warranty.shape)
print("Ebay Dataset Shape:", ebay.shape)

Laptop Dataset Shape: (893, 18)
Warranty Dataset Shape: (893, 18)
Ebay Dataset Shape: (4183, 24)

In [4]:
laptop.head()

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1

In [5]:
warranty.head()

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1

In [6]:
ebay.head()

,Brand,Price,Currency,Color,Features,Condition,Condition Description,Seller Note,GPU,Processor,...,Height of the Display,OS,Storage Type,Hard Drive Capacity,Hard Drive Capacity Unit,SSD Capacity,SSD Capacity Unit,Screen Size (inch),Ram Size,Ram Size Unit
0,other,303.80,$,gray,"Backlit Keyboard, Built-in Microphone, Built...",New,"A brand-new, unused, unopened, undamaged item ...",undefined,intel,quad core,...,1440.0,windows,ssd,512.0,gb,1.0,tb,14,8.0,gb
1,dell,400.00,$,black,"Backlit Keyboard, Bluetooth, Built-in Micropho...",Very Good - Refurbished,The item shows minimal wear and is backed by a...,aaa pcs is a microsoft authorized refurbisher ...,intel,intel core i7 8th generation,...,1080.0,windows,ssd,2.0,tb,NaN,unknown,14,NaN,unknown
2,dell,175.00,$,black,"10/100 LAN Card, Backlit Keyboard, Bluetooth, ...",Used,An item that has been used previously. The ite...,"well kept, fully functional, includes battery,...",intel,intel core i5-6300u,...,1080.0,windows,ssd,500.0,gb,500.0,gb,14,16.0,gb
3,hp,85.00,$,black,"Bluetooth, Built-in Microphone, Built-in Webca...",Good - Refurbished,The item shows moderate wear and is backed by ...,1-year allstate warranty. the original hp char...,intel,intel celeron n,...,768.0,chrome,emmc,16.0,gb,NaN,unknown,11.6,4.0,gb
4,dell,101.25,$,other,"10/100 LAN Card, Built-in Microphone, Built-in...",Good - Refurbished,The item shows moderate wear and is backed by ...,laptops is tested & fully working with some si...,other,intel core i5 6th generation,...,768.0,windows,ssd,NaN,unknown,256.0,gb,12.5,8.0,gb

In [7]:
print("Laptop Columns")
print(laptop.columns)

print("\nWarranty Columns")
print(warranty.columns)

print("\nEbay Columns")
print(ebay.columns)

Laptop Columns
Index(['Unnamed: 0.1', 'Unnamed: 0', 'brand', 'name', 'price', 'spec_rating',
       'processor', 'CPU', 'Ram', 'Ram_type', 'ROM', 'ROM_type', 'GPU',
       'display_size', 'resolution_width', 'resolution_height', 'OS',
       'warranty'],
      dtype='object')

Warranty Columns
Index(['Unnamed: 0.1', 'Unnamed: 0', 'brand', 'name', 'price', 'spec_rating',
       'processor', 'CPU', 'Ram', 'Ram_type', 'ROM', 'ROM_type', 'GPU',
       'display_size', 'resolution_width', 'resolution_height', 'OS',
       'warranty'],
      dtype='object')

Ebay Columns
Index(['Brand', 'Price', 'Currency', 'Color', 'Features', 'Condition',
       'Condition Description', 'Seller Note', 'GPU', 'Processor',
       'Processor Speed', 'Processor Speed Unit', 'Type',
       'Width of the Display', 'Height of the Display', 'OS', 'Storage Type',
       'Hard Drive Capacity', 'Hard Drive Capacity Unit', 'SSD Capacity',
       'SSD Capacity Unit', 'Screen Size (inch)', 'Ram Size', 'Ram Size Unit'],
      dtype='object')

In [8]:
laptop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    object
 3   name               893 non-null    object
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    object
 7   CPU                893 non-null    object
 8   Ram                893 non-null    object
 9   Ram_type           893 non-null    object
 10  ROM                893 non-null    object
 11  ROM_type           893 non-null    object
 12  GPU                893 non-null    object
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    object
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), object(10)
memory usage: 125.7+ KB

In [9]:
warranty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    object
 3   name               893 non-null    object
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    object
 7   CPU                893 non-null    object
 8   Ram                893 non-null    object
 9   Ram_type           893 non-null    object
 10  ROM                893 non-null    object
 11  ROM_type           893 non-null    object
 12  GPU                893 non-null    object
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    object
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), object(10)
memory usage: 125.7+ KB

In [10]:
ebay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4183 entries, 0 to 4182
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Brand                     4183 non-null   object
 1   Price                     4183 non-null   float64
 2   Currency                  4183 non-null   object
 3   Color                     4183 non-null   object
 4   Features                  1993 non-null   object
 5   Condition                 4183 non-null   object
 6   Condition Description     4183 non-null   object
 7   Seller Note               4183 non-null   object
 8   GPU                       4183 non-null   object
 9   Processor                 4183 non-null   object
 10  Processor Speed           2090 non-null   object
 11  Processor Speed Unit      4183 non-null   object
 12  Type                      4183 non-null   object
 13  Width of the Display      1915 non-null   float64
 14  Height of the Display     1915 non-null   float64
 15  OS                        4183 non-null   object
 16  Storage Type              4183 non-null   object
 17  Hard Drive Capacity       1104 non-null   float64
 18  Hard Drive Capacity Unit  4183 non-null   object
 19  SSD Capacity              2127 non-null   float64
 20  SSD Capacity Unit         4183 non-null   object
 21  Screen Size (inch)        2545 non-null   object
 22  Ram Size                  1652 non-null   float64
 23  Ram Size Unit             4183 non-null   object
dtypes: float64(6), object(18)
memory usage: 784.4+ KB

In [11]:
laptop.isnull().sum()

Unnamed: 0.1         0
Unnamed: 0           0
brand                0
name                 0
price                0
spec_rating          0
processor            0
CPU                  0
Ram                  0
Ram_type             0
ROM                  0
ROM_type             0
GPU                  0
display_size         0
resolution_width     0
resolution_height    0
OS                   0
warranty             0
dtype: int64

In [12]:
warranty.isnull().sum()

Unnamed: 0.1         0
Unnamed: 0           0
brand                0
name                 0
price                0
spec_rating          0
processor            0
CPU                  0
Ram                  0
Ram_type             0
ROM                  0
ROM_type             0
GPU                  0
display_size         0
resolution_width     0
resolution_height    0
OS                   0
warranty             0
dtype: int64

In [13]:
ebay.isnull().sum()

Brand                          0
Price                          0
Currency                       0
Color                          0
Features                    2190
Condition                      0
Condition Description          0
Seller Note                    0
GPU                            0
Processor                      0
Processor Speed             2093
Processor Speed Unit           0
Type                           0
Width of the Display        2268
Height of the Display       2268
OS                             0
Storage Type                   0
Hard Drive Capacity         3079
Hard Drive Capacity Unit       0
SSD Capacity                2056
SSD Capacity Unit              0
Screen Size (inch)          1638
Ram Size                    2531
Ram Size Unit                  0
dtype: int64

In [14]:
print("Laptop:", laptop.duplicated().sum())
print("Warranty:", warranty.duplicated().sum())
print("Ebay:", ebay.duplicated().sum())

Laptop: 0
Warranty: 0
Ebay: 0

In [15]:
laptop.describe(include='all')

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
count,893.000000,893.000000,893,893,893.000000,893.000000,893,893,893,893,893,893,893,893.000000,893.000000,893.000000,893,893.000000
unique,NaN,NaN,30,815,NaN,NaN,184,29,7,12,7,2,134,NaN,NaN,NaN,14,NaN
top,NaN,NaN,HP,Inspiron 3525 Laptop,NaN,NaN,12th Gen Intel Core i5 1235U,"Quad Core, 8 Threads",16GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,NaN,NaN,NaN,Windows 11 OS,NaN
freq,NaN,NaN,186,4,NaN,NaN,49,130,456,499,634,872,107,NaN,NaN,NaN,782,NaN
mean,467.135498,521.382979,NaN,NaN,79907.409854,69.379026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.173751,2035.393057,1218.324748,NaN,1.079507
std,270.209769,299.916605,NaN,NaN,60880.043823,5.541555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.939095,426.076009,326.756883,NaN,0.326956
min,0.000000,0.000000,NaN,NaN,9999.000000,60.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.600000,1080.000000,768.000000,NaN,0.000000
25%,235.000000,265.000000,NaN,NaN,44500.000000,66.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.000000,1920.000000,1080.000000,NaN,1.000000
50%,467.000000,531.000000,NaN,NaN,61990.000000,69.323529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.600000,1920.000000,1080.000000,NaN,1.000000
75%,702.000000,784.000000,NaN,NaN,90990.000000,71.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.600000,1920.000000,1200.000000,NaN,1.000000
max,930.000000,1019.000000,NaN,NaN,450039.000000,89.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.000000,3840.000000,3456.000000,NaN,3.000000

In [16]:
warranty.describe(include='all')

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
count,893.000000,893.000000,893,893,893.000000,893.000000,893,893,893,893,893,893,893,893.000000,893.000000,893.000000,893,893.000000
unique,NaN,NaN,30,815,NaN,NaN,184,29,7,12,7,2,134,NaN,NaN,NaN,14,NaN
top,NaN,NaN,HP,Inspiron 3525 Laptop,NaN,NaN,12th Gen Intel Core i5 1235U,"Quad Core, 8 Threads",16GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,NaN,NaN,NaN,Windows 11 OS,NaN
freq,NaN,NaN,186,4,NaN,NaN,49,130,456,499,634,872,107,NaN,NaN,NaN,782,NaN
mean,467.135498,521.382979,NaN,NaN,79907.409854,69.379026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.173751,2035.393057,1218.324748,NaN,1.079507
std,270.209769,299.916605,NaN,NaN,60880.043823,5.541555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.939095,426.076009,326.756883,NaN,0.326956
min,0.000000,0.000000,NaN,NaN,9999.000000,60.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.600000,1080.000000,768.000000,NaN,0.000000
25%,235.000000,265.000000,NaN,NaN,44500.000000,66.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.000000,1920.000000,1080.000000,NaN,1.000000
50%,467.000000,531.000000,NaN,NaN,61990.000000,69.323529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.600000,1920.000000,1080.000000,NaN,1.000000
75%,702.000000,784.000000,NaN,NaN,90990.000000,71.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.600000,1920.000000,1200.000000,NaN,1.000000
max,930.000000,1019.000000,NaN,NaN,450039.000000,89.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.000000,3840.000000,3456.000000,NaN,3.000000

In [17]:
ebay.describe(include='all')

,Brand,Price,Currency,Color,Features,Condition,Condition Description,Seller Note,GPU,Processor,...,Height of the Display,OS,Storage Type,Hard Drive Capacity,Hard Drive Capacity Unit,SSD Capacity,SSD Capacity Unit,Screen Size (inch),Ram Size,Ram Size Unit
count,4183,4183.000000,4183,4183,1993,4183,4183,4183,4183,4183,...,1915.000000,4183,4183,1104.000000,4183,2127.000000,4183,2545,1652.000000,4183
unique,10,NaN,1,20,709,10,10,795,5,413,...,NaN,6,5,NaN,3,NaN,3,66,NaN,3
top,other,NaN,$,other,Touchscreen,Used,An item that has been used previously. The ite...,undefined,other,undefined,...,NaN,windows,unknown,NaN,unknown,NaN,unknown,14,NaN,unknown
freq,1712,NaN,4183,2596,79,2028,2028,3071,2001,1278,...,NaN,1968,2298,NaN,3078,NaN,2054,1009,NaN,2531
mean,NaN,328.130117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,978.471018,NaN,NaN,227.202899,NaN,268.342266,NaN,NaN,20.483656,NaN
std,NaN,387.640478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,294.198849,NaN,NaN,201.231991,NaN,224.996614,NaN,NaN,205.062639,NaN
min,NaN,4.420000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,480.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,NaN,1.000000,NaN
25%,NaN,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,768.000000,NaN,NaN,16.000000,NaN,120.000000,NaN,NaN,4.000000,NaN
50%,NaN,234.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1080.000000,NaN,NaN,256.000000,NaN,240.000000,NaN,NaN,8.000000,NaN
75%,NaN,413.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1080.000000,NaN,NaN,500.000000,NaN,480.000000,NaN,NaN,16.000000,NaN
max,NaN,3900.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2400.000000,NaN,NaN,800.000000,NaN,1024.000000,NaN,NaN,8192.000000,NaN

# Initial Observations

### Laptop Dataset
- Contains laptop specifications and SKU information.
- Will be used as the internal product dataset.

### Warranty Dataset
- Contains warranty claims and component failures.
- Useful for identifying frequently failing components.

### eBay Dataset
- Contains secondary market listings, resale prices, and product conditions.
- Will be matched with internal SKUs to calculate Circularity Score.